updates.pin  = [
  # sbt plugins remain on 2.12.x for now
  { groupId = "org.scala-lang", artifactId = "scala-library", version = "2.12." }
  # depends on https://github.com/raboof/sbt-reproducible-builds/issues/344
  { groupId = "org.scala-sbt", artifactId = "sbt", version = "1." }
]
