name: Scalafmt

permissions: {}

on:
  pull_request:
    branches: ['**']

jobs:
  build:
    name: Code is formatted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check project is formatted
        # https://github.com/jrouly/scalafmt-native-action/pull/363
        uses: raboof/scalafmt-native-action@0f1daa11b1b9abaa574aac6b24a26f14413fd7f8
        with:
          arguments: '--list --mode diff-ref=origin/main'
